// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA7UslueTVTH-zE8HAksg7mtOjZ8b-jsw',
    appId: '1:685337258588:web:9122ddee9973786f7f5499',
    messagingSenderId: '685337258588',
    projectId: 'mywebpage-204a6',
    authDomain: 'mywebpage-204a6.firebaseapp.com',
    storageBucket: 'mywebpage-204a6.firebasestorage.app',
    measurementId: 'G-MBL3C09Y4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPYzzI-3hQhBRdbtLkpjiOw_YDHyf3A8',
    appId: '1:685337258588:android:2d96693d32cb26337f5499',
    messagingSenderId: '685337258588',
    projectId: 'mywebpage-204a6',
    storageBucket: 'mywebpage-204a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cr3RPjWvlDQB-8zW2Y9ZuS-_xT9GDCE',
    appId: '1:685337258588:ios:93ff996ad1258ce97f5499',
    messagingSenderId: '685337258588',
    projectId: 'mywebpage-204a6',
    storageBucket: 'mywebpage-204a6.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cr3RPjWvlDQB-8zW2Y9ZuS-_xT9GDCE',
    appId: '1:685337258588:ios:93ff996ad1258ce97f5499',
    messagingSenderId: '685337258588',
    projectId: 'mywebpage-204a6',
    storageBucket: 'mywebpage-204a6.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA7UslueTVTH-zE8HAksg7mtOjZ8b-jsw',
    appId: '1:685337258588:web:5b6a1501af29af447f5499',
    messagingSenderId: '685337258588',
    projectId: 'mywebpage-204a6',
    authDomain: 'mywebpage-204a6.firebaseapp.com',
    storageBucket: 'mywebpage-204a6.firebasestorage.app',
    measurementId: 'G-3KJ257DVYV',
  );
}
